interface SentimentAnalysisProps {
    comments?: string;
}

const SentimentAnalysis = ({ comments }: SentimentAnalysisProps) => {
    // Basic logic to determine sentiment from text
    const getSentiment = (text: string): "CRITICAL" | "POSITIVE" | "NEUTRAL" => {
        if (!text) return "NEUTRAL";
        const lowercase = text.toLowerCase();
        const positiveWords = ["great", "excellent", "good", "happy", "exceptional", "success", "growth", "improvement", "satisfied"];
        const negativeWords = ["poor", "bad", "unhappy", "fail", "critical", "issue", "concern", "disappointed", "struggle"];

        let score = 0;
        positiveWords.forEach(w => { if (lowercase.includes(w)) score++; });
        negativeWords.forEach(w => { if (lowercase.includes(w)) score--; });

        if (score > 0) return "POSITIVE";
        if (score < 0) return "CRITICAL";
        return "NEUTRAL";
    };

    const sentiment = getSentiment(comments || "");

    const config = {
        CRITICAL: {
            label: "CRITICAL",
            bg: "bg-[#f87171]",
            emoji: "😔",
            textColor: "text-[#f87171]"
        },
        POSITIVE: {
            label: "POSITIVE",
            bg: "bg-[#4ade80]",
            emoji: "😊",
            textColor: "text-[#4ade80]"
        },
        NEUTRAL: {
            label: "NEUTRAL",
            bg: "bg-[#fbbf24]",
            emoji: "😐",
            textColor: "text-[#fbbf24]"
        },
    };

    const current = config[sentiment];

    return (
        <section className="space-y-12 pt-12 pb-32">
            <div className="space-y-4 text-center border-t border-gray-100 pt-24">
                <h2 className="text-2xl font-black text-gray-800 tracking-tight">AI Sentiment Analysis</h2>
                <p className="text-sm text-gray-400 leading-relaxed max-w-2xl mx-auto">
                    Based on the feedback captured during your review session, we performed an AI-driven Sentiment Analysis. The analysis indicates the discussion sentiment was <span className={`font-black uppercase ${current.textColor}`}>{current.label}</span>
                </p>
            </div>

            <div className="flex justify-center">
                <div className="bg-white rounded-[32px] border border-gray-100 shadow-[0_20px_50px_rgba(0,0,0,0.08)] overflow-hidden w-full max-w-2xl transition-all hover:shadow-[0_20px_60px_rgba(0,0,0,0.12)]">
                    <div className={`${current.bg} py-4 text-center`}>
                        <span className="text-xs font-black text-white uppercase tracking-[0.2em]">{current.label}</span>
                    </div>
                    <div className="py-12 flex flex-col items-center justify-center space-y-8">
                        <style>
                            {`
                                @keyframes float {
                                    0% { transform: translateY(0px) rotate(0deg); }
                                    50% { transform: translateY(-15px) rotate(2deg); }
                                    100% { transform: translateY(0px) rotate(0deg); }
                                }
                                .animate-premium-float {
                                    animation: float 4s ease-in-out infinite;
                                }
                            `}
                        </style>
                        <div className="relative">
                            <span className="text-8xl animate-premium-float filter drop-shadow-2xl select-none block">
                                {current.emoji}
                            </span>
                            <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 w-20 h-2 bg-black/5 blur-md rounded-full"></div>
                        </div>
                        <div className="w-24 h-1.5 bg-[#f3f4f6] rounded-full opacity-60"></div>
                    </div>
                </div>
            </div>
            <footer className="pt-24 text-center border-t border-gray-100">
                <p className="text-[11px] text-gray-400 font-bold tracking-tight">
                    © 2025 TalentSpotify Performance Management System • Generated by TARA AI
                </p>
            </footer>
        </section>
    );
};

export default SentimentAnalysis;
